### PR TITLE
Add Python 3.6, drop Python 3.3

### PR DESCRIPTION
**Pull request by jamadden**
- Badge readme
- Add coveralls and tox coverage environment
- Install ZCML deps as test deps for 100% coverage and to test
  configure.zcml on CI.

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
lgtm

**Comment by jamadden** [comment]
Thank you! Could we get a PyPI release (or the relevant access) when convenient?

**Comment by mgedmin** [comment]
You've PyPI access now.

**Comment by jamadden** [comment]
Thank you. 4.2.0 has been released to PyPI.

**Pull request merged**
